spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false
    username: demo_user
    password: demo_user
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    schemas: demo_db
    locations: classpath:db/migration
    out-of-order: true
    placeholder-prefix: '${{'
    placeholder-suffix: '}}'
